### ISSUE TITLE
Issues with 0.2.0-alpha Release

### ISSUE THREAD

**Issue by Robo56** [WElRD/OverCollect#2]
I tried updating just the OverCollect.jar and the lib folder and also just a fresh restart of 0.2.0-alpha and the app won't start. I'm not sure what is causing the issue, but 0.1.10-alpha release is still working perfectly fine.

**Comment by ichbineinebanane** [comment]
I have the same issue. The 'pure Java' option still works, but trying to launch the ffmpeg.bat (or just Overcollect.jar) results in the command prompt window appearing and disappearing without anything happening.

The OverCollect-ffmpeg.out file should be attached.
[OverCollect-ffmpeg.txt](https://github.com/WElRD/OverCollect/files/1043010/OverCollect-ffmpeg.txt)

**Comment by Robo56** [comment]
Yea I think I didn't have ffmpeg setup correctly or something. The 0.2.1-alpha java is working perfectly fine.

**Comment by ichbineinebanane** [comment]
Interesting, I still can't get it to work. Did you have to manually install the ffmpeg libraries?

**Comment by Robo56** [comment]
Sorry I wasn't exactly clear. I was not able to get ffmpeg working correctly, but I was able to use the java only .bat from 0.2.1-alpha without issues.

**Comment by shaunidiot** [comment]
Same problem here. Opening the ffmpeg bat file only resulted in open and closing of the command prompt. The jar bat file still works though. 

Edit: Crash logs same as above.
```
2017-06-01 18:38:35	INFO	de.rcblum.overcollect.OverWatchCollectorApp	Loading capture engine: de.rcblum.overcollect.capture.FFMpegCaptureEngine
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:413)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2597)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:386)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:380)
	at de.rcblum.overcollect.capture.FFMpegCaptureEngine.<init>(FFMpegCaptureEngine.java:69)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at de.rcblum.overcollect.OverWatchCollectorApp.<init>(OverWatchCollectorApp.java:178)
	at de.rcblum.overcollect.OverWatchCollectorApp.main(OverWatchCollectorApp.java:116)
```

**Comment by VVEIRD** [comment]
The problem lies within the library JavaCV, used for the ffmpeg capture. I'll look into it as soon as I have the time for it, probably sunday.

As of now, could you please post your os, e.g. Windows 10 pro x64 etc.

Thank you.

**Comment by shaunidiot** [comment]
Laptop
Windows 10 Pro x64
Intel i7-6700HQ
16GB RAM
NVIDIA GeForce GTX 1060 6GB

Not sure what's needed, so I'll post the basics. Thanks :)

**Comment by Robo56** [comment]
I'm currently Windows 10 Pro x64 as well.

**Comment by ichbineinebanane** [comment]
Windows 10 Pro x64 here too.

If there is any other info I can provide you with to help, feel free to hit me up!

**Comment by Kawo83** [comment]
Its working great with java only, but i prefer to play fullscreen. Waiting for the ffmpeg fix to try again. Good work

**Comment by ichbineinebanane** [comment]
@WElRD After seeing your comment on the other thread I checked and found that I had been using the 32bit version of Java as well. After installing the 64bit version the ffmpeg.bat worked perfectly.

**Comment by Robo56** [comment]
I'm checking that when I get home as well. Thanks for the input!

**Comment by Kawo83** [comment]
is this app still in development?

**Comment by VVEIRD** [comment]
Yes it is still in developement. Sadly I haven't found the time recently to develop more (Private thins, work etc.).

For the issue: It seems that using 64-bit java solves the issue, I'll edit the donwoload description with the requirement.

**Comment by Kawo83** [comment]
Its working with java 64Bit, but it does not detect anything in fullscreen for me. I have 144 Hz refresh rate. Could this be the issue nothing is found? In windowed mode all works fine

**Comment by ichbineinebanane** [comment]
@Kawo83 I'm playing on a 2 monitor setup with my main screen running at 144Hz fullscreen as well and got it to work by downloading the 64bit Java version. Are you sure you are running the ffmpeg version? Java only will not work in fullscreen.

**Comment by Kawo83** [comment]
Yes i am pretty sure. ffmpeg is in the logs and program runs with 64Bit Java. But nothing gets detected. I have a SLI setup and 144 Hz. Game is running arround 230-260 FPS. As soon as I change to windowed mode it works fine (even with ffmpeg)
